sudo: false
language: python
python:
  - "pypy"
  - "pypy3"
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - nightly
allow_failures:
  - "pypy3"
  - nightly
os:
  - linux
git:
  depth: 3
branches:
  only:
  - /.*/
install:
  - pip install .[TESTS]
script:
  - pytest