sudo: false
language: python
matrix:
  fast_finish: true
  include:
    - python: "pypy"
    - python: "pypy3"
    - python: "2.7"
    - python: "3.6"
    - python: "3.5"
    - python: "3.4"
    - python: nightly
  allow_failures:
    - python: "pypy3"
    - python: nightly
os:
  - linux
git:
  depth: 3
branches:
  only:
  - /.*/
install:
  - pip install .[TESTS]
script:
  - pytest